customers/urls.py
from django.urls import path

from customers import views
from customers import pdfviews,billviews
from customers import exportviews



app_name='customer_app'

urlpatterns=[
    path('create/',views.create,name='create'),
    # path('',views.CustomerPagination.as_view(),name="customer_pagination"),#it assists to show page
    path('list/',views.index,name='list'),#assists to show data
    path('edit/',views.edit,name='edit'),#here i pass primary key
    path('search/',views.search,name="search"),
    path('delete/',views.delete,name="delete"),
    path('customer-id-<int:cid>/order/',views.cus_ord_view,name="view"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('orders/bill/<int:cid>',billviews.GenerateBILL.as_view(),name="bill"),
    path('export/',exportviews.export,name="export"),
    
]

orders/urls.py
from django.urls import path
from orders import views,pdfviews

app_name = "order_app"

urlpatterns = [
    path('create/<int:cid>/', views.create, name = "create"),#I pass cid as for instance to show customer name when i click Add Order
    path('list/',views.index,name="list"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('edit/customer-id-<int:cid>/order-id-<int:oid>/',views.edit,name="edit"),
    path('search/',views.search,name="search"),
    path('delete/<int:oid>/',views.delete,name="delete"),
    
]





rms/urls.py
from django.contrib import admin
from django.urls import path,include
# from registers.views  import dashboard

from registers import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView




urlpatterns = [
	path('admin/', admin.site.urls),
	path('',views.first_page,name="home"),
	path('dashboard/',views.dashboard,name="dashboard"),

#    path('',include('django.contrib.auth.urls')),
	
	path('user/',include('registers.urls', namespace = 'register_app')),
	path('customers/',include('customers.urls', namespace="customer_app")),
	path('products/',include('products.urls', namespace="product_app")),#namespace is the app_name in products.urls
	path('orders/',include('orders.urls', namespace="order_app")),

	
	
#    path('',include('registers.profile_urls',namespace="view_app")),

	path('reset_password/',auth_views.PasswordResetView.as_view(template_name = 'passwordreset/password_reset_email.html'), 
		name = "password_reset"),
	
	path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset/password_reset_sent.html'), 
		name = "password_reset_done"),
	
	path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/password_reset_form.html'),
		name="password_reset_confirm"),  
	
	#<token> check  for valid user or not--><uidb64> user id encoded in base 64--this email is sent to the user
	#<uidb64> helps to know user who request for password
	path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/password_reset_complete.html'),
		name="password_reset_complete"),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




customers/models.py
from django.db import models
class Customer(models.Model):
   
    name=models.CharField(max_length=50,null=True)
    email=models.CharField(max_length=50)
    contact=models.CharField(max_length=50)
    date_created=models.DateTimeField(auto_now=True)
    # status=models.BooleanField()    
      
    def __str__(self):
        return self.name
    class Meta:
        db_table = 'tbl_customers'
        
    def save(self,*args,**kwargs):
    	super().save(*args,**kwargs)
    
    
          
    # def save(self,*args,**kwargs):
    #     if not self.id:
    #         self.slug=slugify(self.first_name)
    #     super(Customer,self).save(self,*args,**kwargs):





    
        

    
    
    
    
    

  
    
    
    

    
    
    
    
    
    

orders/models.py
from django.db import models

# Create your models here.

from customers.models import Customer
from products.models import Product

class Order(models.Model):
    status=(
        ('Pending','Pending'),
        ('Delivered','Delivered'),
        ('Out for delivery','out for delivery')   
    )
    
    customer=models.ForeignKey(Customer,null=True,on_delete=models.SET_NULL)#customer_id is foreign key in tbl_orders
    '''this means if Customer is deleted then I want to set Order to NULL value in database but dont want to delete
        -if on_delete = models.CASCADE then deleting on Customer will also delete Order which is bad practice
    '''
    #Producat and Customer associated with Order
    product=models.ForeignKey(Product,null=True,on_delete=models.SET_NULL)#maila order table Product ko dtails pauxu
    '''
    Similarly if Product is deleted then order set to Null value'''
    
    created_at=models.DateTimeField(max_length=50,null=True,auto_now=True)
    status=models.CharField(max_length=100,null=True,choices=status)
    quantity = models.IntegerField(default=1,blank=False)
    # total_price = models.DecimalField(max_digits=5,decimal_places=2,default=0)
    
    
    # def __str__(self):
    #     return self.product.name  #w/ relationship
    class Meta:
        db_table = 'tbl_orders'
    
    
    def save(self,*args,**kwargs):
    	super().save(*args,**kwargs)

    
    
    @property
    def get_total_item_price(self):#for particular product order total
        return self.quantity * self.product.price
    
    
    
    # def get_total_discount_item_price(self):
    #         return self.quantity * self.product.discount_price

    # def get_amount_saved(self):
    #     return self.get_total_item_price() - self.get_total_discount_item_price()

    # def get_final_price(self):
    #     if self.product.discount_price:
    #         return self.get_total_discount_item_price()
    #     return self.get_total_item_price()
    

    
    

customers/forms.py




from django import forms
from django.forms import ModelForm
from .models import Customer

# class CustomerForm(forms.Form):
 
#     full_name=forms.CharField(max_length=50,required=True)
#     email=forms.CharField(max_length=50,required=True)
#     contact=forms.CharField(max_length=50,required=True)
#     status=forms.BooleanField(required=False)
    
    # status=forms.BooleanField(required=False)
    

class CustomerModelForm(ModelForm):
    
    name=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Full Name",}))
    email=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Email",}))
    contact=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Contact",}))
   
    class Meta:
        model=Customer
        fields=['name','email','contact']



 
 
 
    
        
        
     
        

    
    
    
    
    
    
    
    

orders/forms.py
from django import forms

from .models import Order,Product,Customer


# from products.models import Product
# from customers.models import Customer


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        

        exclude = ('total_price',)

customers/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import request,JsonResponse
from django.core import serializers
# from django.contrib.auth.decorators import login_required

from customers.models import Customer
from orders.models import Order
from products.models import Product
# from django.contrib.auth.models import User

from django.contrib import messages
from customers.forms import CustomerModelForm
from customers.filters import CustomerFilter
from django.contrib import messages
from django.utils import timezone
from django.views.generic import ListView,DetailView#for pagination
from django.views.generic import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.template.loader import render_to_string

from django.db.models import Q
from django.contrib.auth.decorators import login_required


'''
-->Before i use go to customers/create url to get form and use this create function separately but when i use j query i have to render form in same page.i.e customers/list
page.So,I only use index form as i render from there in context
def create(request):
	
	form=CustomerModelForm()
	 
	if(request.method=='POST'):
		form=CustomerModelForm(request.POST)#form post ma show hunxa 
		if(form.is_valid()):
			form.save()
		   
		return redirect('/customers/list?success')
	
			
	return render(request,'customers/create.html',{'form':form})#first ma yo page dekhinxa
'''

# class CustomerPagination(ListView,DetailView):
#     model = Customer
#     # queryset = Customer.objects.all()--if I write i dont need to write query set ---use either
#     template_name = 'customers/copindex.html'  # Default: <app_label>/<model_name>_list.html
#     context_object_name = 'customers' #retrieve data from database
#      # Default: object_list i.e contexxt i use in copindex.html--Customer.objects.all() ko data tanxa
#     paginate_by = 5
#     ordering = ['-created_at']#Suppose you want the books whhile concerning with the book to be ordered in the page by their created date descending.
#      # Default: Model.objects.all()
	
   
# this is the class based view
# class IndexView(CustomerPagination,View):
	
	# def get(self,request,*args,**kwargs):
	#     form = CustomerModelForm()
	#     customers=Customer.objects.all()  
	#     myFilter = CustomerFilter(request.GET,queryset=customers)
	#     customers = myFilter.qs
	#     context={
	#     'customers':customers,'myFilter':myFilter,'form':form
	#     }
	   
	#     return render(request,'customers/copindex.html',context)
	
	# def post(self,request,*args,**kwargs):
	#     form = CustomerModelForm(request.POST)
	#     if form.is_valid():
	#         form.save()
	#     return redirect('/customers/list?customer added successfully')
			
		
@login_required(login_url = '/user/login/')     
def index(request):
	form = CustomerModelForm()
	customers=Customer.objects.all().order_by("-id")
	myFilter = CustomerFilter(request.GET,queryset=customers)
	customers = myFilter.qs#for searchng
	
	#pagination logic
	customer_count = customers.count()
	  

	   
	page = request.GET.get('page', 1)#means page  number 1
	
	# if page and page.isdigit():
	#     page = int(page)
	# else:
	#     page = 5
		
	# paginator = Paginator(customers, 5)#5 data per page
	paginator = Paginator(customers, 10)
  
	try:
		customers = paginator.page(page)
	except PageNotAnInteger:
		customers = paginator.page(1)
	except EmptyPage:
		#if page is out of range show last page
		customers = paginator.page(paginator.num_pages)

	

	context={
		'customers':customers,#this is for both pagination and table list use(blc table list also should support pagination.so dont pass data for list separately)
  		
    	'myFilter':myFilter,
		'form':form,'page':page,
		'customer_count':customer_count,
		'start': customers.start_index(),
		'end': customers.end_index(),
		}
	return render(request,'customers/copindex.html',context)



#I use function base view but use class base view to inherit index.I am just copying index code 
def search(request):
	data = dict()
	field_value = request.GET.get('query')#grab the input value
	print(field_value)
	
	# products = Product.objects.all()
	# myFilter = ProductFilter(request.GET,queryset=products)
	# products = myFilter.qs

	if field_value:
		customers = Customer.objects.filter(
											Q(name__contains=field_value)
											|Q(email__icontains=field_value) 
											| Q(contact__contains=field_value)  
											|Q(date_created__contains=field_value)                      
											)
	
		context = {'customers': customers}
		data['html_list'] = render_to_string('customers/get_search_customers.html',context,request=request)
		return JsonResponse(data)
	else:
		customers = Customer.objects.all()
		context = {'customers': customers}
		data['html_list'] = render_to_string('customers/get_search_customers.html',context,request=request)
		return JsonResponse(data)





def create(request):    
	if request.method=="POST":
		form=CustomerModelForm(request.POST)
		if form.is_valid():
			cid =request.POST['cusid']
			name=request.POST.get("name")
			email=request.POST.get("email")
			contact=request.POST.get("contact")
		
			
			if(cid==''):
				customer=Customer(name=name,email=email,contact=contact)
			else:
				customer=Customer(id = cid,name=name,email=email,contact=contact)
				
			customer.save()
			prod=Customer.objects.values()
			# print(prod,"--------------------------")
			customer_data =list(prod)
			
			return JsonResponse({'status':'Save','customer_data':customer_data,'message':'Customer is successfully submitted'},safe=False)
		else:
			return JsonResponse({'status':0},safe=False)

def edit(request):
    if request.method=="POST":
        id=request.POST.get('cid')
        print(id)
        customer=Customer.objects.get(pk=id)
        customer_data={"id":customer.id,"name":customer.name,"email":customer.email, "contact":customer.contact}
	
        return JsonResponse(customer_data,safe=False)


	
def delete(request):
    if request.method=="POST":
        id=request.POST.get('cid')
        pi=Customer.objects.get(pk=id)
        pi.delete()

        return JsonResponse({'status':1,'message':'Customer is successfully deleted'},safe=False)
    else:
        return JsonResponse({'status':0,'message':'Failed to delete data'},safe=False) 




def cus_ord_view(request, cid):
	# order = Order.objects.filter(customer__first_name="Shankar") 
	# -->I am retrieving  the order the  particular person 

	customer = get_object_or_404(Customer,pk=cid) #use to get beautiful error -u can also use below
	# customer = Customer.objects.get(pk = cid)#return a particular customer name according to choosen primary key
	orders = customer.order_set.all()#particular customer ko particular order select garxa--It is possible with customer id
	#here order in  order_set is attribute 
	#Order ma Customer is foreign key so ot os possible to use order_set with customer
	order_count = orders.count()
	order_count = orders.count()    
	customer_total_order_price=0.00
	
	for order in customer.order_set.all():
		per_total_price = float(order.product.price) * order.quantity
		# customer.per_total = per_total_price--to get the price of respective products
		#return value of first product i.e first row
		customer_total_order_price += per_total_price
		
	

	context = {'customer_total_price':customer_total_order_price,'customers':customer, 'orders':orders, 'order_count':order_count,'order_num':order_count}
	return render(request,'customers/orderview.html',context)

	

	#     else:
	#         messages.info(request, "This item was not in your cart")
	#         return redirect("/customers/orders/",pk = cid)
	# else:
	#     messages.info(request, "You do not have an active order")
	#     return redirect("/customers/orders/",pk = cid)

		
		
	
	
	# order_item = get_object_or_404(Order, pk=cid)
	# if order_item.quantity > 1:
	#     order_item.quantity -= 1
	#     order_item.save()
				
	# else:
	#     order.Order.remove(order_item)
		
		
	# messages.info(request, "This item quantity was updated.")
	# return redirect("/customers/orders/",pk = cid)
	
	
	
	



	
	

customers/templates/customers/copindex.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load static %}

{% block title %}Customers{% endblock %}

{% block javascript %}
<script src="{% static 'vendor/js/scripts.js' %}"></script>
<script src="{% static 'products/search.js' %}"></script>
<script src="{% static 'customers/scroll.js' %}"></script>
{% endblock %}

{% block content %}
<!--Nav bar and side bar which include search and others-->

{% include 'navbar.html' %}


<br><br>
<hr>

<!--for messages tag-->

{% include 'message.html' %}

   
   

<div class="row">
    <div class="col-lg-10" style="margin-left:15%;">
          <div class="alert alert-success" id="upt_success" style="display:none">

          </div>
           <div class="alert alert-danger" id="upt_error" style="display:none">

          </div>
    </div>
</div>


<div class="col">
    <div class="card border-dark" style="margin-left:18%;padding-right:15%;padding:10px;margin-bottom:10px;">
        <h3 class="card-header"> Customers Details</h3>

    </div>
</div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-left:18%;">

        {% include "customers/formsearch.html" %}

        <button class="navbar-toggler mt-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <button data-toggle="modal" data-target="#AddCustomer" class=" btn btn-primary mt-1 ml-2">

                    <i class=" fas fa-plus "></i> Customer
                    <!-- I dont need to use url because Add Customer garda data-target la id search gardai janxa id ma -->
                    </button>
            </li>
            <li class="nav-item">
                <a type="button" class="btn btn-primary mt-1 ml-2" href="{% url 'customer_app:export' %}"><i class="fas fa-file-export"></i> Export</a>
            </li>
           
            <li class="nav-item">
                <a type="button" href="{% url 'customer_app:pdf' %}" class="btn  btn-danger mt-1 ml-2"><i class="fas fa-file-pdf"></i> PDF</a>
            </li>

          
          </ul>
          <button  style="margin-left:40%;" onclick = " scrollToBottom()" class="btn btn-primary mt-2"> <i class="fas fa-arrow-alt-circle-down fa-1x "></i>
          </button>

          
        </div>
      </nav>
    <hr>




{% include 'includes/customer_list.html' %}
{% include 'includes/add_edit_form.html' %}<!--This is for showing model add/edit  customer-->



<button  id="back-to-top" style="float:right;margin-right:1%;" class="btn btn-primary"> <i class="fas fa-arrow-alt-circle-up fa-1x"></i>
</button>


<script>

    $(document).ready(function(){


        $(".btn-insert-data").click(function(e){
            console.log("button click")

            e.preventDefault();
            e.stopPropagation(); 
    
            output="";

           var cid=$("#cusid").val();// <input type="hidden" name="cusid" id="cusid" /> inside modal form in includes/add_edit_form.html 
            var name=$("#id_name").val();
            var email=$("#id_email").val();
          
            var contact=$("#id_contact").val();
            let csr = $("input[ name=csrfmiddlewaretoken]").val();
            
            if(name==""){
                $("#ins_error").text("Please Enter Name")//ins_error is below the form(look id in includes/add_edit_form.html )
                $("#ins_error").show()
                return;
            }
            else if(email==""){
                $("#ins_error").text("Please Enter email")
                $("#ins_error").show()
                return;
            }
            else if(contact==""){
                $("#ins_error").text("Please Enter Contact Number")
                $("#ins_error").show()
                return;
              return;
            }
            else{
    
            
                $.ajax({
                 
                    url : '{% url "customer_app:create" %}',
                    method:'POST',
                    data:{cusid:cid,name:name,email:email,contact:contact,csrfmiddlewaretoken:csr},
                    
    
                })
                
                .done(function(data){//response bring all the data
                    console.log(data.customer_data)
    
    
                            x=data.customer_data
                            if(data.status=="Save"){

                              //  $("#msg").text("Form Submitted Successfully");
                              //  $("#msg").show();
                            
                                 $("#AddCustomer .close").click();
                                 $("#upt_error").hide();
                                 $("#upt_success").text(data.message);
                                $("#upt_success").show();
    
                             
    
                                for(i=0;i<x.length;i++){

                                    output+=
                                    `
                                    <tr>
                                        <td> <a href="customers/customer-id-${x[i].id}/order/" class="btn btn-primary btn-sm">
                                            <i class="fa fa-eye"></i></a>
                                        </td>
                                        <td> ${x[i].id}</td>
                                        <td> ${x[i].name}</td>
                                        <td> ${x[i].email}</td>
                                        <td> ${x[i].contact}</td>
                                        <td>${x[i].date_created}</td>
                                        <td>
                                            <button type='button' class='btn btn-success btn-sm  btn-edit' data-target="#AddCustomer" data-toggle="modal"   data-cid=" ${x[i].id}" ><i class='fa fa-edit'></i></button>    <button type='button' class='btn btn-danger  btn-sm  btn-del'  data-cid=" ${x[i].id}" ><i class='fa fa-trash-alt'></i></button>     <a href='' class='btn btn-success btn-sm'>  <i class='fas fa-plus'></i> </a>
                                        </td>
                                     
                                    </tr>
                                    `
                                  
                                    $(".table tbody").html(output);
        }
        }
       
    
    
                  
                })
             
                .fail(function(){
                     $("#ins_success").hide();//
                     $("#ins_error").text("Something Went Wrong!");
                     $("#ins_error").show();
                })
                .always(function(){
                    $(".btn-insert-data").removeAttr("disabled");
                   $(".btn-insert-data").text("Save");
                })
    
    
    
   //  setInterval('location.reload()', 1300);  
    
            }
        })
    
      //edit form
        $("tbody").on("click",".btn-edit",function(){
            let id=$(this).attr("data-cid");
            let csr = $("input[ name=csrfmiddlewaretoken]").val();
            mydata={cid:id,csrfmiddlewaretoken:csr}
            $.ajax({
                url:"{% url 'customer_app:edit' %}",
                method:"POST",
                data:mydata,
    
                success:function(data){
                    if(data.status == 1){
    
                        $("#upt_success").text(data.message);
                        $("#upt_success").show();
                    
    
                    }
    
                  
                    $("#cusid").val(data.id);//<input type="hidden" name="cusid" id="cusid" /> in includes/add_edit_form.html
                    $("#id_name").val(data.name);
                    $("#id_email").val(data.email);
                    $("#id_contact").val(data.contact);
                    
    
                   
                }
                
            })
        })
    
       //Delete data
       $("tbody").on("click",".btn-del",function(){
           
        let id=$(this).attr("data-cid");
        let csr = $("input[ name=csrfmiddlewaretoken]").val();
        mydata={cid:id,csrfmiddlewaretoken:csr}
        mythis=this;
        $.ajax({
            url:"{% url 'customer_app:delete' %}",
            method:"POST",
            data:mydata,
            success:function(data){
    
               
                if(data.status==1){
    
    
    
                   $("#upt_error").hide();
                    $("#upt_success").text(data.message);
                   $("#upt_success").show();
                    $(mythis).closest("tr").fadeOut();
    
                   
                }
                if(data.status==0){
                    $("#upt_success").hide();
                        $("#upt_error").text(data.message);
                        $("#upt_error").show();
                }
            }
        })
    })

    })
  

    
</script>

{% endblock%}



customers/templates/customers/get_search_customers.html
{% for customer in customers %}<!--This customers should be the data of pagination-->
<tr>

    <td><a href="{% url 'customer_app:view' customer.id %}" class="btn btn-primary btn-sm"><i
                class="fa fa-eye"></i></a></td>
    <td>{{customer.id}}</td>
    <td>{{customer.name}} </td>
    <td>{{customer.email}}</th>
    <td>{{customer.contact}}</td>
    <td>{{customer.date_created}}</td>
    <td>
        <button type="button" data-cid="{{customer.id}}" data-target="#AddCustomer" data-toggle="modal" class="btn btn-success btn-sm btn-edit ">
            <i class="fas fa-edit"></i>

            {% if request.user.is_superuser %}
            <button type="button" data-cid="{{customer.id}}"
                class="ml-1 btn btn-danger btn-sm btn-del"><i
                    class="fas fa-trash-alt"></i></button>
            {% endif %}

            <a href="{% url 'order_app:create' customer.id %}" class="btn btn-success btn-sm">
                <i class="fas fa-plus"></i>
            </a>

    </td>
</tr>
{% empty %}
<tr>
    <td colspan="7" class=" text-center alert alert-danger">No Product Found</td>
</tr>

{% endfor %}

customers/templates/customers/orderview.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Customer-Order{% endblock %}

{% block javascript %}

<script src="{% static 'vendor/js/scripts.js' %}"></script>

{% endblock %}

{% block content %}

{% include 'navbar.html' %}

<br><br><br>

{% include 'message.html' %}

<div class="container">
   <div class="row">
       <div class="col-md ml-4">
        <div style="margin-left:80px;">
            <div class="card bg-primary text-center text-white ml-2 mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{order_count}}</h5>
                </div>
            </div>
        </div>
       </div>
       <div class="col-md">
        <div style="margin-left:80px;">
            <div class="card bg-info text-center text-white ml-2 mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Price</h5>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{customer_total_price}}</h5>
                </div>
            </div>
        </div>
       </div>
   </div>
<hr>

   <div class="row">
    <div class="col">


        <div class="card border-dark" style="margin-left:26%; ">
            <h3 class="card-header" style="text-align: center;"> Order Details of <strong>{{customers.name}}</strong>
            </h3>
        </div>
    </div>

    <div class="col-md-2" style="margin-right:20%;">
        <a href=" {% url 'customer_app:bill' customers.id  %}" class="btn  btn-primary mt-2 float-right">Print
            Invoice</a>
    </div>
</div>
   

<hr>
            <div class="col-md-10" style="margin-left:15%;">
                <table class="table table-responsive-sm table-sm table-hover text-nowrap table-striped table-bordered">
                    <thead class="thead-dark">
                        <tr style="text-align: center;">


                            <th>Product</th>

                            <!-- <th>Category</th> -->
                            <th>Created</th>
                            <th>Status</th>
                            <th>Quantity</th>
                            <th>Per Price</th>
                            <th> Subtotal</th>
                            <th>Action</th>

                        </tr>


                    </thead>
                    <tbody>

                        {% for order in orders %}

                        <tr>

                            <td>{{order.product.name}}</th>
                            <!-- <td>{{order.product.category}}</td> -->

                            <!--
        <td>{{order.product}}</th> also give same result for name
   maila order table ma Product table ko access garda use product object
   like above
   product=models.ForeignKey(Product,null=True,on_delete=models.SET_NULL)
   -->

                            <td>{{order.created_at}}</td>
                            <td>{{order.status}}</td>
                            <td>
                               
                                {{order.quantity}} {{order.product.unit}}
                             
                            </td>
                            <td>{{order.product.price}}</td>
                            <td>{{order.get_total_item_price}}</td>
                            <!--to get price for each row product call get_total_item_price in models.py of orders-->

                            <!-- <td>{{customer.per_total}}</td> -->

                            <td><a href="{% url 'order_app:edit' order.customer.id order.id %}"
                                    class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>

                                    
                                <a href="{% url 'order_app:delete' order.id%}" class="btn btn-danger btn-sm"><i
                                        class="fa fa-trash-alt"></i></a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="8" style="text-align: center;" class="alert alert-danger">
                             <strong> Order is empty.Please Place the Order!
                            </td></strong>
                        </tr>

                        {% endfor %}


                    </tbody>
                </table>
                
               

            
       

    </div>
</div>


{% endblock%}