orders/urls.py
from django.urls import path
from orders import views,pdfviews

app_name = "order_app"

urlpatterns = [
    path('create/<int:cid>/', views.create, name = "create"),#I pass cid as for instance to show customer name when i click Add Order
    path('list/',views.index,name="list"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('edit/customer-id-<int:cid>/order-id-<int:oid>/',views.edit,name="edit"),
    path('search/',views.search,name="search"),
    path('delete/<int:oid>/',views.delete,name="delete"),
    
]





registers/urls.py
from django.urls import path

from registers import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetDoneView

app_name ='register_app'

urlpatterns = [
    path('login/',views.loginPage,name="login"),
    path('register/',views.SignupView,name="register"),
    path('logout/',views.UserLogout.as_view(),name="logout"),
    path('profile/',views.UserProfile,name="user_view"),

    # path('dash/<int:cid>/',views.dashboard_data,name = "dash-price-data")

    # path('logout/',a)

    
]





'''
for which email is sent use SMTP configuration in settings.py
https://docs.djangoproject.com/en/3.0/topics/auth/default/
Submit email form    -->PasswordResetViews.as_views()
email sent success  -->PasswordResetDoneView.as_views()
Link to password reser form in email ---user see email   -->PasswordResetConfirmView.as_views()
password sucessfully changed message and user can login using new password   -->PasswordResetCompleteView.as_views()


-------------------------------------------------------------
-->python decouple concept for email and other things secrete|
--------------------------------------------------------------
'''

rms/urls.py
from django.contrib import admin
from django.urls import path,include
# from registers.views  import dashboard

from registers import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView




urlpatterns = [
	path('admin/', admin.site.urls),
	path('',views.first_page,name="home"),
	path('dashboard/',views.dashboard,name="dashboard"),

#    path('',include('django.contrib.auth.urls')),
	
	path('user/',include('registers.urls', namespace = 'register_app')),
	path('customers/',include('customers.urls', namespace="customer_app")),
	path('products/',include('products.urls', namespace="product_app")),#namespace is the app_name in products.urls
	path('orders/',include('orders.urls', namespace="order_app")),

	
	
#    path('',include('registers.profile_urls',namespace="view_app")),

	path('reset_password/',auth_views.PasswordResetView.as_view(template_name = 'passwordreset/password_reset_email.html'), 
		name = "password_reset"),
	
	path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset/password_reset_sent.html'), 
		name = "password_reset_done"),
	
	path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/password_reset_form.html'),
		name="password_reset_confirm"),  
	
	#<token> check  for valid user or not--><uidb64> user id encoded in base 64--this email is sent to the user
	#<uidb64> helps to know user who request for password
	path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/password_reset_complete.html'),
		name="password_reset_complete"),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




templates/base.html

{% load static %}

<!DOCTYPE html>
<html lang="en">

    {% block head %}

<head>
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  
    <!-- <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>  -->
 
   
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>

    

      <!--link for index.html dashboard -->
      <link href="{% static 'vendor/css/styles.css' %}" rel="stylesheet" />
      

      <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js"
          crossorigin="anonymous"></script>


 
  

    <title> {% block title %}  {% endblock %}</title>
    

</head>
    {% endblock %}


<body>

  <div class="container">
    {% block content %}{% endblock %}
</div>

  
   

    {% block javascript %}
    {% endblock %}

    {% block css %}
    {% endblock %}

</body>
</html>



templates/message.html


<div style="margin-left:18%;" >

  {% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" id ="message_container">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
 
   
</div>

templates/navbar.html

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        {% if request.user.is_superuser %}
        <a class="navbar-brand" href="/">
            <i class="fas fa-home"></i> Home
        </a>

        {% else %}

        <a class="navbar-brand" href="/">
            <i class="fas fa-home"></i> Home
        </a>


        {% endif %}
             <button type="button" id="sidebarToggle" class="btn btn-warning text-black-50">
                <i class="fas fa-align-left"></i>
              </button>

            <div class="col">
                
                <a class="float-right" style="color:white;"> Hello, {{request.user.username}} </a>
               
            </div>
      
<div class="col">
    <div  data-toggle="modal" data-target="#logOutModal" style="margin-left:70%;">
             
        <a class="btn btn-sm btn-warning float-right" style="cursor: pointer;color:black;"><i class="fa fa-sign-out-alt"></i> LOGOUT</a>
    </div>
</div>

     
        
    </nav>
    <!--logout model js popup for confirm or stay-->
    <div id="logOutModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Want to leave ?</h4>
                    <button class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    Press logout to leave !
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" data-dismiss="modal">
                        <!--model-dismiss la same page ma lauxa-->
                        Stay Here
                    </button>
                    <a class="btn btn-danger" href="{% url 'register_app:logout'%}">
                        Logout</a>
                </div>
            </div>
        </div>
    </div>

    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">

                  {% if request.user.is_superuser %}
                        <a class="nav-link" href="/dashboard">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-home"></i>
                            </div>
                            Dashboard
                        </a>
                {% endif %}

                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                            aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-columns"></i>
                            </div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="(collapse)" id="collapseLayouts" aria-labelledby="headingOne"
                            data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{% url 'product_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Products</span></a>
                                <a class="nav-link" href="{% url 'order_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Orders</span></a>
                                <a class="nav-link" href="{% url 'customer_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Customers</span></a>
                            </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                            aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-book-open"></i>
                            </div>
                            Authentication
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="(collapse)" id="collapsePages" aria-labelledby="headingTwo"
                            data-parent="#sidenavAccordion">
                            
                            <nav class="sb-sidenav-menu-nested nav">
                                {% if user.is_authenticated %}

                                <a class="nav-link" href="{% url 'register_app:logout'%}"><i class="fas fa-sign-out-alt"></i> Logout</a>

                                {% else %}
                                <a class="nav-link" href="{% url 'register_app:login'%}">Login</a>
                                <a class="nav-link" href="{% url 'register_app:register'%}">Register</a>
                                {% endif %}
                            </nav>




                        </div>
                       
                    </div>
                </div>
              
            </nav>
        </div>




    </div>
    </div>


</body>