products/urls.py


from django.urls import path

from products import views
from products import pdfviews


app_name = 'product_app'

urlpatterns=[
    path('create/',views.create, name="create"),
    path('list/',views.index, name = "list"), 
    path('search',views.search,name="search"),
    path('pdf/',pdfviews.GeneratePDF.as_view(),name="pdf"),
    path('edit/',views.edit,name="edit"),
    path('delete/',views.delete,name="delete_product"),
    path('productData/<int:cid>/',views.productData,name="product-data")
]

rms/urls.py
from django.contrib import admin
from django.urls import path,include
# from registers.views  import dashboard

from registers import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView




urlpatterns = [
	path('admin/', admin.site.urls),
	path('',views.first_page,name="home"),
	path('dashboard/',views.dashboard,name="dashboard"),

#    path('',include('django.contrib.auth.urls')),
	
	path('user/',include('registers.urls', namespace = 'register_app')),
	path('customers/',include('customers.urls', namespace="customer_app")),
	path('products/',include('products.urls', namespace="product_app")),#namespace is the app_name in products.urls
	path('orders/',include('orders.urls', namespace="order_app")),

	
	
#    path('',include('registers.profile_urls',namespace="view_app")),

	path('reset_password/',auth_views.PasswordResetView.as_view(template_name = 'passwordreset/password_reset_email.html'), 
		name = "password_reset"),
	
	path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset/password_reset_sent.html'), 
		name = "password_reset_done"),
	
	path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/password_reset_form.html'),
		name="password_reset_confirm"),  
	
	#<token> check  for valid user or not--><uidb64> user id encoded in base 64--this email is sent to the user
	#<uidb64> helps to know user who request for password
	path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/password_reset_complete.html'),
		name="password_reset_complete"),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)




products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    
    category=(
                ('indoor service','indoor service'),
                ('outdoor service','outdoor service')
)

    PRICE_UNITS_CHOICES = (
    #   The first element in each tuple is the actual value to be set on the model, and the second element is the human-readable name.
        ('', 'Choose Product Unit'),
        ('kg', 'kg'),
        ('l','litre'),
        ('pcs','pcs'),
        ('gm','gm'),
        ('m2', 'm2'),
        ('m3', 'm3'),
        ('ml', 'ml'),

    )
    name=models.CharField(max_length=50,null=True)
    price=models.DecimalField(max_digits=20,decimal_places=2)
    quantity = models.IntegerField(blank=False,default=1)
    unit = models.CharField(max_length= 50,choices = PRICE_UNITS_CHOICES,default='')
    # slug = models.SlugField(max_length=80,default=False)
    category=models.CharField(max_length=200,null=True,choices=category)
    description=models.CharField(max_length=50,null=True)
    created_at=models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.name
    class Meta:
        db_table = 'tbl_products'
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

class HistConf(models.Model):
	item = models.ForeignKey(Product, on_delete=models.CASCADE)
	actual= models.PositiveSmallIntegerField()#it is the actual quantity that is b4 deleting or adding 
	transition = models.IntegerField()#it is the quantity no that is added or deleted
	total = models.PositiveSmallIntegerField()#quantity remains after adding or removing 
	user = models.CharField(max_length=50)
	time = models.DateTimeField(auto_now=True,null=True)

	@classmethod
	def create(cls, actual, transition, pid, user=''):
		hist = cls(actual=actual, transition=transition, total=actual+transition, user=user, time=datetime.datetime.now(), item=pid)
		return hist

	def __str__(self):
		return f"Before: {self.actual} Change: {self.transition} After: {self.total} by user: {self.user} at {self.time}"




products/forms.py

from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    
    name=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Product Name",}))
    price=forms.DecimalField(widget=forms.TextInput(attrs={"placeholder": " Enter Price",}))
    quantity=forms.IntegerField(widget=forms.TextInput(attrs={"placeholder": " Enter Quantity",}))    
    description=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Product Description",}))
    class Meta:
        model=Product
        # fields=['name','price','category','description']
        fields = '__all__'
        exclude = ('category',)
    
        
    #i dont need to write form.CharField to show form only but to show design i need

    ''' name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'input',
            
            'class':'form-control',
            'class':'col-md-6',
            # # 'class':'form-group',
            'placeholder':'Enter Product Name'
            
        } ))
    
    price = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'class':'col-md-6',
            # 'class':'form-group',
            'placeholder':'Enter Price'
        }     ))
    
    # category = forms.CharField(widget=forms.TextInput(
    #     attrs={
    #         'class':'form-control',
    #         'class':'col-md-6',
    #         # 'class':'form-group',
        
    #     }     ))
    
    description = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'class':'col-md-6',
            # 'class':'form-group',
            'placeholder':'Describe Product'
        }     ))
'''

customers/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import request,JsonResponse
from django.core import serializers
# from django.contrib.auth.decorators import login_required

from customers.models import Customer
from orders.models import Order
from products.models import Product
# from django.contrib.auth.models import User

from django.contrib import messages
from customers.forms import CustomerModelForm
from customers.filters import CustomerFilter
from django.contrib import messages
from django.utils import timezone
from django.views.generic import ListView,DetailView#for pagination
from django.views.generic import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.template.loader import render_to_string

from django.db.models import Q
from django.contrib.auth.decorators import login_required


'''
-->Before i use go to customers/create url to get form and use this create function separately but when i use j query i have to render form in same page.i.e customers/list
page.So,I only use index form as i render from there in context
def create(request):
	
	form=CustomerModelForm()
	 
	if(request.method=='POST'):
		form=CustomerModelForm(request.POST)#form post ma show hunxa 
		if(form.is_valid()):
			form.save()
		   
		return redirect('/customers/list?success')
	
			
	return render(request,'customers/create.html',{'form':form})#first ma yo page dekhinxa
'''

# class CustomerPagination(ListView,DetailView):
#     model = Customer
#     # queryset = Customer.objects.all()--if I write i dont need to write query set ---use either
#     template_name = 'customers/copindex.html'  # Default: <app_label>/<model_name>_list.html
#     context_object_name = 'customers' #retrieve data from database
#      # Default: object_list i.e contexxt i use in copindex.html--Customer.objects.all() ko data tanxa
#     paginate_by = 5
#     ordering = ['-created_at']#Suppose you want the books whhile concerning with the book to be ordered in the page by their created date descending.
#      # Default: Model.objects.all()
	
   
# this is the class based view
# class IndexView(CustomerPagination,View):
	
	# def get(self,request,*args,**kwargs):
	#     form = CustomerModelForm()
	#     customers=Customer.objects.all()  
	#     myFilter = CustomerFilter(request.GET,queryset=customers)
	#     customers = myFilter.qs
	#     context={
	#     'customers':customers,'myFilter':myFilter,'form':form
	#     }
	   
	#     return render(request,'customers/copindex.html',context)
	
	# def post(self,request,*args,**kwargs):
	#     form = CustomerModelForm(request.POST)
	#     if form.is_valid():
	#         form.save()
	#     return redirect('/customers/list?customer added successfully')
			
		
@login_required(login_url = '/user/login/')     
def index(request):
	form = CustomerModelForm()
	customers=Customer.objects.all().order_by("-id")
	myFilter = CustomerFilter(request.GET,queryset=customers)
	customers = myFilter.qs#for searchng
	
	#pagination logic
	customer_count = customers.count()
	  

	   
	page = request.GET.get('page', 1)#means page  number 1
	
	# if page and page.isdigit():
	#     page = int(page)
	# else:
	#     page = 5
		
	# paginator = Paginator(customers, 5)#5 data per page
	paginator = Paginator(customers, 10)
  
	try:
		customers = paginator.page(page)
	except PageNotAnInteger:
		customers = paginator.page(1)
	except EmptyPage:
		#if page is out of range show last page
		customers = paginator.page(paginator.num_pages)

	

	context={
		'customers':customers,#this is for both pagination and table list use(blc table list also should support pagination.so dont pass data for list separately)
  		
    	'myFilter':myFilter,
		'form':form,'page':page,
		'customer_count':customer_count,
		'start': customers.start_index(),
		'end': customers.end_index(),
		}
	return render(request,'customers/copindex.html',context)



#I use function base view but use class base view to inherit index.I am just copying index code 
def search(request):
	data = dict()
	field_value = request.GET.get('query')#grab the input value
	print(field_value)
	
	# products = Product.objects.all()
	# myFilter = ProductFilter(request.GET,queryset=products)
	# products = myFilter.qs

	if field_value:
		customers = Customer.objects.filter(
											Q(name__contains=field_value)
											|Q(email__icontains=field_value) 
											| Q(contact__contains=field_value)  
											|Q(date_created__contains=field_value)                      
											)
	
		context = {'customers': customers}
		data['html_list'] = render_to_string('customers/get_search_customers.html',context,request=request)
		return JsonResponse(data)
	else:
		customers = Customer.objects.all()
		context = {'customers': customers}
		data['html_list'] = render_to_string('customers/get_search_customers.html',context,request=request)
		return JsonResponse(data)





def create(request):    
	if request.method=="POST":
		form=CustomerModelForm(request.POST)
		if form.is_valid():
			cid =request.POST['cusid']
			name=request.POST.get("name")
			email=request.POST.get("email")
			contact=request.POST.get("contact")
		
			
			if(cid==''):
				customer=Customer(name=name,email=email,contact=contact)
			else:
				customer=Customer(id = cid,name=name,email=email,contact=contact)
				
			customer.save()
			prod=Customer.objects.values()
			# print(prod,"--------------------------")
			customer_data =list(prod)
			
			return JsonResponse({'status':'Save','customer_data':customer_data,'message':'Customer is successfully submitted'},safe=False)
		else:
			return JsonResponse({'status':0},safe=False)

def edit(request):
    if request.method=="POST":
        id=request.POST.get('cid')
        print(id)
        customer=Customer.objects.get(pk=id)
        customer_data={"id":customer.id,"name":customer.name,"email":customer.email, "contact":customer.contact}
	
        return JsonResponse(customer_data,safe=False)


	
def delete(request):
    if request.method=="POST":
        id=request.POST.get('cid')
        pi=Customer.objects.get(pk=id)
        pi.delete()

        return JsonResponse({'status':1,'message':'Customer is successfully deleted'},safe=False)
    else:
        return JsonResponse({'status':0,'message':'Failed to delete data'},safe=False) 




def cus_ord_view(request, cid):
	# order = Order.objects.filter(customer__first_name="Shankar") 
	# -->I am retrieving  the order the  particular person 

	customer = get_object_or_404(Customer,pk=cid) #use to get beautiful error -u can also use below
	# customer = Customer.objects.get(pk = cid)#return a particular customer name according to choosen primary key
	orders = customer.order_set.all()#particular customer ko particular order select garxa--It is possible with customer id
	#here order in  order_set is attribute 
	#Order ma Customer is foreign key so ot os possible to use order_set with customer
	order_count = orders.count()
	order_count = orders.count()    
	customer_total_order_price=0.00
	
	for order in customer.order_set.all():
		per_total_price = float(order.product.price) * order.quantity
		# customer.per_total = per_total_price--to get the price of respective products
		#return value of first product i.e first row
		customer_total_order_price += per_total_price
		
	

	context = {'customer_total_price':customer_total_order_price,'customers':customer, 'orders':orders, 'order_count':order_count,'order_num':order_count}
	return render(request,'customers/orderview.html',context)

	

	#     else:
	#         messages.info(request, "This item was not in your cart")
	#         return redirect("/customers/orders/",pk = cid)
	# else:
	#     messages.info(request, "You do not have an active order")
	#     return redirect("/customers/orders/",pk = cid)

		
		
	
	
	# order_item = get_object_or_404(Order, pk=cid)
	# if order_item.quantity > 1:
	#     order_item.quantity -= 1
	#     order_item.save()
				
	# else:
	#     order.Order.remove(order_item)
		
		
	# messages.info(request, "This item quantity was updated.")
	# return redirect("/customers/orders/",pk = cid)
	
	
	
	



	
	

products/templates/products/formsearch.html
<form method="GET" action="{% url 'product_app:search' %}" id="js-search-form" class="form-inline" >
    {% csrf_token %}
    
            <input class="form-control mr-sm-2"  type="search" name="query" placeholder="Search..." aria-label="Search"
            aria-describedby="basic-addon2" />        
        <button class="btn btn-primary mt-1">Search</button>
     

</form>


products/templates/products/get_search_products.html
  
                        {% for product in products%}

                        <tr>

                            <!-- <td>{{order.product.name}}</td> -->
                      
                            <td>{{product.id}}</td>
                            <td>{{product.name}}</td>
                            <td>{{product.price}}</th>

                            <td>{{product.description}}</td>
                            <td>{{product.quantity}} {{product.unit}}</td>
                            <td>{{product.created_at}}</td>


                            <td>
                                <button type="button" data-pid = "{{product.id}}" data-target="#AddProduct" data-toggle="modal"
                                    class="btn btn-success btn-sm btn-edit ">
                                    <i class="fas fa-edit"></i>

                                    {% if request.user.is_superuser %}
                                    <button type="button" data-pid = "{{product.id}}"
                                        class="ml-1 btn btn-danger btn-sm btn-del"><i
                                            class="fas fa-trash-alt"></i></button>
                                        {% endif %}
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                          <td colspan="7" class=" text-center alert alert-danger">No Products Found</td>
                        </tr>       

                        {% endfor %}

                    

products/templates/products/index.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block javascript %}

<script src="{% static 'vendor/js/scripts.js' %}"></script>
<script src="{% static 'products/products.js' %}"></script>
<script src="{% static 'products/search.js' %}"></script>

{% endblock %}

{% block title %}Products{% endblock%}

{% block content %}

<!--Nav bar and side bar which include search and others-->

{% include 'navbar.html' %}


<br><br>
<hr>



<div class="row">
    <div class="col-lg-10" style="margin-left:15%;">
          <div class="alert alert-success" id="upt_success" style="display:none">

          

          </div>
           <div class="alert alert-danger" id="upt_error" style="display:none">

            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>

          </div>
    </div>
</div>



<div class="col">
    <div class="card border-dark" style="margin-left:18%;padding-right:15%;padding:10px;margin-bottom:10px;">
        <h3 class="card-header"> Product Details</h3>

    </div>
</div>


<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-left:18%;">

    {% include "products/formsearch.html" %}
    
   
    <button class="navbar-toggler mt-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse mt-2" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item active">

            {% if request.user.is_authenticated %}
            <button type=" button "  data-target="#AddProduct" data-toggle="modal" class=" btn btn-primary ml-2 mb-2 ">
        
                <i class=" fas fa-plus "></i> Product
                <!-- I dont need to use url because Add Customer garda data-target la id search gardai janxa id ma -->
            </button>
            {% endif %}
            
        </li>
        <li class="nav-item ">
            <a href="{% url 'product_app:pdf' %}" class="btn  btn-danger ml-2"> <i class="fas fa-file-pdf"></i> PDF</a>
        </li>

      </ul>
    
    </div>
  </nav>

<hr>



{% include 'includes/product_list.html' %}


{% include 'includes/product_add_edit_form.html' %}



<div class="row">

    <div class="col mt-2" style="margin-left:19%;position:fixed;">


        <Strong> Showing {{start}} to {{end}} of {{products_count}} products</Strong>


    </div>

    <div class="col" >


        <div style="float:right;margin-right: 20%;">

            {% if products.has_other_pages %}
            <ul class="pagination">
                {% if products.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ products.previous_page_number }}">Previous</a>
                {% else %}

                {% endif %}

                {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                <!--recent page ma dark dekhauxa-->
                <li class="btn btn-info mb-4"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}

                <li><a class="btn btn-outline-info mb-4" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}

                {% if products.has_next %}

                <a class="btn btn-outline-info mb-4" href="?page={{ products.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ products.paginator.num_pages }}">Last</a>
                {% else %}
                <!-- <li class="btn btn-outline-info mb-4"><span>&raquo;</span></li> -->
                {% endif %}
                <hr>
            </ul>
            {% endif %}
        </div>
    </div>
</div>


 <script>
   $(document).ready(function(){

    $("#btn-insert-data").click(function(e){

        e.preventDefault();
        e.stopPropagation();
        console.log("button clicked")
        
        output="";

        var pid=$("#proid").val();// <input type="hidden" name="proid" id="proid" /> inside modal form in includes/add_edit_form.html 
        var name=$("#id_name").val();
        var price=$("#id_price").val();
        var quantity=$("#id_quantity").val();
        var unit=$("#id_unit").val();
        var description=$("#id_description").val();
        let csr = $("input[ name=csrfmiddlewaretoken]").val();//if i use this and pass to url then i dont need to use csrf_exempt(somewhat not secure so use this way) in views
        
        if(name==""){
            $("#ins_error").text("Please, Enter Product Name")//ins_error is below the form(look id in includes/add_edit_form.html )
            $("#ins_error").show()
            return;
        }
        else if(price==""){
            $("#ins_error").text("Please Enter Price")
            $("#ins_error").show()
            return;
        }
        else if(quantity==""){
            $("#ins_error").text("Please Enter Quantity")
            $("#ins_error").show()
            return;
        } else if(unit==""){

            $("#ins_error").text("Please Choose Unit")
            $("#ins_error").show()
            return;
        } else if(description==""){
            $("#ins_error").text("Please Enter product Description")
            $("#ins_error").show()
            return;
        }
        else{

            $.ajax({
             
                url : "{% url 'product_app:create' %}",
                method:"POST",
                dataType:'json',
              
                data:{proid:pid,name:name,price:price,quantity:quantity,unit:unit,description:description,csrfmiddlewaretoken:csr},
               


                success:function(data){//response bring all the data
                    
                            x=data.product_data//I accept data in list

                            if(data.status=="Save"){
                                console.log(data.product_data)
    
                            
                            
                               $("#AddProduct .close").click();
                                $("#upt_error").hide();
                                 $("#upt_success").text(data.message);
                                 $("#upt_success").show();
    
    
                                for(i=0;i<x.length;i++){
                                    output+=
                                    "<tr><td>"+
                                        x[i].id+
    
                                        "</td><td>"+
                                            x[i].name+
    
                                        "</td><td>"+
                                            x[i].price+
    
                                        "</td><td>"+
                                            x[i].description+
    
                                        "</td><td> "+
                                            x[i].quantity+" <span data-type = 'unit'> "+x[i].unit+" </span>"+
                                        
                                    
                                        "</td> <td>"+
                                            x[i].created_at+
    
                            "</td> <td><button type='button' class='btn btn-success btn-sm  btn-edit' data-target='#AddProduct' data-toggle='modal'   data-pid="+x[i].id+" ><i class='fa fa-edit'></i></button>    <button type='button' class='btn btn-danger  btn-sm  btn-del'  data-pid="+x[i].id+" ><i class='fa fa-trash-alt'></i></button>"+
    
                               
                                    "</td></tr>";
    
    
                                    $(".table tbody").html(output);
                                    $("#proid").val('');
                                    $("form")[0].reset();
                    }

                    if(data.status==0){
                        $("#msg").text("Unable to Save Data");
                        $("#msg").show();
                        $("#stuid").val('');
                        $("form")[0].reset();
                    }
        }              
                }
            })

           // setInterval('location.reload()', 10000);  
        }
    })

  //edit form
    $("tbody").on("click",".btn-edit",function(){
        
        let id=$(this).attr("data-pid");
        let csr = $("input[ name=csrfmiddlewaretoken]").val();
        mydata={pid:id,csrfmiddlewaretoken:csr}

        $.ajax({
            url:"{% url 'product_app:edit' %}",
            method:"POST",
            data:mydata,
            dataType:"json",

            success:function(data){//means after get particular data it to edit it
                console.log(data)
                console.log("edited")
                if(data.status == 1){

                    $("#upt_error").hide();
                    $("#upt_success").text(data.message);
                   $("#upt_success").show();

                }

              //Logic to show the data to the form so as to edit it.

              //{id: 273, name: "Peanut Butter", price: "600.00", quantity: 49, unit: "kg", …}  example for this data

                $("#proid").val(data.id);//I dont want to see id when click on edit so i use hidden type but it should be pass to views
                //<input type="hidden" name="proid" id="proid" /> in includes/add_edit_form.html
                $("#id_name").val(data.name);
                $("#id_price").val(data.price);
                $("#id_quantity").val(data.quantity);
                $("#id_unit").val(data.unit);
                $("#id_description").val(data.description);

               
            }
            
        })
    })

   //Delete data
   $("tbody").on("click",".btn-del",function(){

 
    
    let id=$(this).attr("data-pid");
    let csr = $("input[ name=csrfmiddlewaretoken]").val();
    mydata={pid:id,csrfmiddlewaretoken:csr}
    mythis=this;

    $.ajax({
        url:"{% url 'product_app:delete_product' %}",
        method:"POST",
        data:mydata,
        success:function(data){
          //  console.log("success delete")

           
            if(data.status==1){



               $("#upt_error").hide();
                $("#upt_success").text(data.message);
               $("#upt_success").show();
                $(mythis).closest("tr").fadeOut();

               
            }
            if(data.status==0){
                $("#upt_success").hide();
                    $("#upt_error").text(data.message);
                    $("#upt_error").show();
            }
        }
    })
})

    


   });
</script>

{% endblock %}


products/templates/products/pdf.html
{% extends 'base.html' %}

{% block title%}Customer Details{% endblock %}

{% block content %}
      
        <style type="text/css">
            body {
                
                font-size: 13px;
            
            }
            .header {
                font-size: 25px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }

            tr:first-child{
                outline: thin solid transparent;
                height: 40px;
              }
           
        </style>
        

         
            

       
        <div class='wrapper'>
            <div class='header'>
                
                <p class='title'>Products Invoice </p>
            </div>
            <div class='details'>
              Date : {{myDate}}
                <hr class='hrItem' />
            </div>
        </div>
        <br>

        <div class="container">
            <div class="col-md-12">
        
                <table class="table" border="1">
                    <thead>
                        <tr>
                         
                            <th>Id</th>
                            <th>Name</th>

                            <th>Per Price</th>
                           
                            <th>Description</th>
                            <th>Quantity</th>
                           

                        </tr>
                    </thead>
                    <tbody>
                        {% for product in products%}

                        <tr style="text-align: center;">

                        
                            <td>{{product.id}}</td>
                            <td>{{product.name}}</td>
                            <td>{{product.price}}</th>
                          
                            <td>{{product.description}}</td>
                            <td>{{product.quantity}}</td>
                           


                       
                        </tr>

                        {% endfor %}
                    </tbody>
                </table>
        
    </div>
</div> 

{% endblock %}

products/templates/products/update.html


{% load widget_tweaks %}
{% load crispy_forms_tags %}



{% block content %}


<form method="post" >
    
    <div class="modal-header">
       
        <h4 class="modal-title">Update Product</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        {% csrf_token %}

        {{update_form|crispy}}

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Update Product</button>
    </div>
</form>


{% endblock%}